
const Data = [
  // --------------------------------------Mobile toilet Trolley---------------------
  
  {
       id: 1,
      name: "8 Seater Mobile Toilet",
      Description:"The 8 Seater Mobile Toilet is a portable restroom solution ideal for events and construction sites. It features eight stalls for high capacity, with essential amenities for cleanliness and comfort. Its mobile design allows for easy transportation and setup.",
      img: "/image/img/8 Seater Mobile Toilet.jpg",
      features1: "Eight Seater Mobile Toilet Trolley ",
      features2: "Hand Sanitizers: Equipped with hand sanitation stations for hygiene.",
      feature3: "Waste Management System: Efficient waste disposal for cleanliness.",
       Wheel : "No of wheel- 4",
       Compartment:"No of Comapartment- 8",
       Tank:"  Tank Capacity- 1500L",
        Brand:"Brand- HHES",
        Built:" Built Type-Modular",
        Wall:"Wall  Type-FRP",
        category:"mobile-toilet-trolley"
     },
  {
       id: 2,
      name: "Indian Style Four Seater Toilet Trolley",
      Description:"The 8 Seater Mobile Toilet is a portable restroom solution ideal for events and construction sites. It features eight stalls for high capacity, with essential amenities for cleanliness and comfort. Its mobile design allows for easy transportation and setup.",
      img: "/image/img/Four Seater Toilet Trolley.webp",
      features1: "Four Individual Stalls: Designed to accommodate multiple users simultaneously.",
      features2: "Fiberglass Reinforced Plastic (FRP) Construction: Durable, lightweight, and resistant to corrosion.",
      feature3: "Compact Design: Easy to maneuver and fit in various locations.",
       Wheel : "No of wheel- 4",
       Compartment:"No of Comapartment- 4",
       Tank:"  Tank Capacity- 500L",
        Brand:"Brand- HHES",
        Built:" Built Type-Modular",
        Wall:"Wall  Type-FRP",
        category:"mobile-toilet-trolley"
     },
     {
        id: 3,
        name: " Ten Seater Mobile Toilet Trolley",
        Description:"This  Ten Seater Mobile Toilet Van is manufactured with the use of quality examined components and cutting edge techniques. Also, the offered van is integrated with water inlet and waste management system. It is used during some special occasions such as marriages, receptions, fairs and beach parties from a remote distance to the city. We offer this van to provide temporary toilet facilities along with proper electrical lighting fittings and ventilation. Also, the provided van is demanded at construction sites.",
        img: "/image/img/ten seated.webp",
        features1: "Available with ten toilet cabins",
        features2: "Resistance against extreme weather conditions",
        feature3: "Smooth and easy transportation",
         Wheel : "No of wheel- 4",
         Compartment:"No of Comapartment- 10",
         Tank:"  Tank Capacity- 2000L",
         Brand:"Brand- HHES",
         Built:" Built Type-Modular",
         Wall:"Wall  Type-FRP" , 
         category:"mobile-toilet-trolley"

       },

       {
          id: 4,
          name: "Six Seater Mobile Toilet Trolley (Indian Style)",
          Description:"Six Seater Mobile Toilet Trolley. It is widely utilized in slum areas, construction sites, and villages. This trolley is comprised of 6 toilet cabins, 3 on either side with a robust door. It is also constructed with an extra area for placing a large tank to ensure appropriate water supply for proper hygiene. Six Seater Mobile Toilet Trolley offered by us is coated with a vibrant blue colored paint to make it rust proof in nature.",
          img: "/image/img/Six Seater Mobile Toilet Trolley.png",
          features1: "Installed with ceramic toilet seats",
          features2: "Has a spacious area for outside the cabins",
          feature3: "Ergonomically designed",
           Wheel : "No of wheel- 4",
           Compartment:"No of Comapartment- 6",
           Tank:"  Tank Capacity- 500L",
           Brand:"Brand- HHES",
           Built:" Built Type-Modular",
           Wall:"Wall  Type-FRP",
           category:"mobile-toilet-trolley"
        },
        {
            id: 5,
            name: "Four Seater Mobile Toilet",
            Description:"We are emerging as one of the fastest growing companies, engaged in manufacturing and supplying of Four Seater Mobile Toilet Van. It is installed 4 toilet cabins with 2 on each side, a water tank enclosed by an extended platform, and proper drainage system. This toilet van gives the flexibility to be transported to desired area without any hassle. Its complete structural frame is constructed using premium quality iron with a paint coating to increase the life. Offered Four Seater Mobile Toilet Van also consists of two wheels for its easy movement with the help of a vehicle.",
            img: "/image/img/Four Seater on 2 Wheal embossing.png",
            features1: "Has a hinge on the front for attachment to carrying truck",
            features2: "Leak proof piping system",
            feature3: "Strong structure",
             Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 2",
             Tank:"  Tank Capacity- 500L",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"mobile-toilet-trolley"
          },



           // --------------------------------------Single Seater Portable Toilet Cabin---------------------
  

           {
            id: 6,
            name: "Urinal Toilet Cabin",
            Description:"The Urinal Toilet Cabin is a compact restroom solution ideal for high-traffic areas like events and construction sites. It features multiple urinals for quick access and reduced wait times. Made from durable materials, it ensures weather resistance and easy maintenance. With a focus on hygiene, it often includes hand sanitizers and proper drainage. Its portable design allows for easy setup and relocation.",
            img: "/image/img/Single-Urinal-toilet.png",
            features1: "Hygiene Features: Often includes hand sanitizers and proper drainage systems.",
            features2: "Compact Design: Space-efficient, making it suitable for crowded areas.",
            feature3: "Durable Materials: Built to withstand outdoor conditions and frequent use.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 100 Ltr Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Single Seater Portable Toilet Cabin"
          },
           {
            id: 7,
            name: "FRP Portable Toilet Cabin (Indian Style)",
            Description:" FRP Portable Toilet Cabin (Indian Style) is used as reliable and cost effective restroom solution for common people under different circumstances. Featured with 4 pillar based construction, this FRP toilet cabin is designed with FRP roof and wall, FRP door and window. Water storage capacity 100 ltr. approx. of Single Seated Indian Style Toilet Cabin. Sludge tank is 200 liter of Single Seated Indian Style Toilet Cabin.  approx. . Cabinet like shape, color coated plain surface, weather proof housing and trouble free erection on ground are the key aspects of this toilet cabin.",
            img: "/image/img/FRP IWC with Uninal.png",
            features1: "Ventilation System: Enhances airflow to reduce odors and improve comfort.",
            features2: "Compact Size: Space-efficient, making it ideal for various locations.",
            feature3: "Portable Design: Easy to transport and set up for temporary or mobile use.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 200 Ltr Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Single Seater Portable Toilet Cabin"
          },

           // -------------------------------------- Toilet Cabin---------------------

           {
            id: 8,
            name: "Single Seater Portable Toilet cabin",
            Description:" The Single Seater Portable Toilet Cabin is a compact restroom solution for individual use, perfect for events and construction sites. Made from durable materials, it ensures weather resistance and easy maintenance. Its portable design allows for quick setup and relocation.",
            img: "/image/img/Single Seater Portable Toilet cabin 1.webp",
            features1: "Has a strong & compact structure",
            features2: "Metallic shed is welded to assure safety",
            feature3: "Short platform height makes it suitable for aged people as well",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 200 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
           {
            id: 9,
            name: "FRP Portable Toilet Cabin( Urinal Style)",
            Description:" The FRP Portable Toilet Cabin (Urinal Style) is a compact restroom solution designed for high traffic. It features multiple urinals and is made from durable fiberglass reinforced plastic for weather resistance. Its portable design allows for easy setup and relocation, ensuring hygiene and convenience.",
            img: "/image/img/FRP Portable Toilet Cabin( Urinal Style).png",
            features1: "Durable FRP Construction: Lightweight and resistant to corrosion and weather elements.",
            features2: "Compact Design: Space-efficient, ideal for crowded areas and events.",
            feature3: "Ventilation: Provides airflow to minimize odors.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 200 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
           {
            id: 10,
            name: "Portable Toilet Cabin (Indian Style)",
            Description:" The Portable Toilet Cabin (Indian Style) is a compact restroom solution designed for traditional squat toilet use. Ideal for outdoor events, construction sites, and rural areas, it offers privacy and comfort. Constructed from durable materials, it ensures easy maintenance and weather resistance.",
            img: "/image/img/3 seater portable toilet cabin.png",
            features1: "Indian Style Design: Accommodates traditional squat toilets.",
            features2: "Durable Construction: Made from robust materials for long-lasting use.",
            feature3: "Ventilation: Ensures airflow to reduce odors.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 3",
             Tank:"  Tank Capacity- 300 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
           {
            id: 11,
            name: "FRP Portable Toilet Cabin (Western Style)",
            Description:"The FRP Portable Toilet Cabin offers a durable and modern solution for outdoor restrooms. Made from fiberglass-reinforced plastic, it ensures easy maintenance and weather resistance, featuring a spacious interior with contemporary fixtures. Perfect for events, construction sites, and festivals.",
            img: "/image/img/FRP Portable Toilet Cabin (Western Style).jpeg",
            features1: "Spacious Interior: Provides ample room for comfort and ease of use.",
            features2: "Easy Maintenance: Smooth surfaces simplify cleaning and upkeep.",
            feature3: "Lightweight Design: Easy to transport and set up at different locations.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 100 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },   
           {
            id: 12,
            name: "02 FRP Portable Toilet Cabin (Indian Style)",
            Description:"The FRP Portable Toilet Cabin in Indian style offers a practical and hygienic solution for outdoor sanitation needs. Crafted from durable fiberglass-reinforced plastic, it provides a spacious and comfortable environment, ideal for events, festivals, and construction sites.",
            img: "/image/img/02 FRP Portable Toilet Cabin (Indian Style).png",
            features1: "Durable Material: Made from fiberglass-reinforced plastic for longevity and resilience.",
            features2: "Spacious Design: Ample interior space for comfortable use.",
            feature3: "Easy to Clean: Smooth surfaces facilitate quick and efficient maintenance.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 2",
             Tank:"  Tank Capacity- 200 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
           {
            id: 13,
            name: "Portable Toilet Cabin western & Urinal Style",
            Description:"The Portable Toilet Cabin in Western and Urinal style is designed for modern sanitation needs at outdoor events, construction sites, and festivals. This cabin features a clean and functional design, with dedicated spaces for both toilets and urinals, ensuring convenience and privacy for users.",
            img: "/image/img/Portable Toilet Cabin (western & Urinal Style).webp",
            features1: "Durable Materials: Constructed from high-quality, weather-resistant materials for long-lasting durability.",
            features2: "Durable Construction: Made from high-quality, weather-resistant materials for long-lasting use.",
            feature3: "User-Friendly Fixtures: Equipped with modern toilets and urinals for a hygienic experience.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 2",
             Tank:"  Tank Capacity- 200 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
           {
            id: 14,
            name: "Portable Toilet Cabin ( western Style)",
            Description:"The Portable Toilet Cabin in Western style offers a modern and hygienic solution for outdoor sanitation needs. Ideal for events, festivals, and construction sites, it provides a comfortable and private restroom experience with a user-friendly design.",
            img: "/image/img/FRP Portable Toilet Cabin (Western Style).jpeg",
            features1: "Spacious Interior: Ample room for comfort and ease of movement inside the cabin.",
            features2: "Modern Fixtures: Equipped with contemporary toilets and sinks for a clean experience.",
            feature3: "Portable Design: Lightweight and easy to transport, making it suitable for various locations..",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 100 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
          {
            id: 15,
            name: "Western Style Single Seater Portable Toilet Cabin",
            Description:"The Western Style Single Seater Portable Toilet Cabin provides a compact and efficient solution for outdoor sanitation. Designed for individual use, it combines comfort and privacy, making it ideal for events, festivals, and construction sites.",
            img: "/image/img/Western Style Single Seater Portable Toilet Cabin.jpg",
            features1: "Toilet cabin is designed with FRP roof and wall, FRP door and window.",
            features2: "Modern Fixtures: Equipped with contemporary toilets and sinks for a clean experience.",
            feature3: "Easy Access: User-friendly door with secure locking for privacy.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 100 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },
          {
            id: 16,
            name: "FRP Portable Toilet Cabin ( Indian Style)",
            Description:"The FRP Portable Toilet Cabin in Indian style offers a practical and hygienic sanitation solution for outdoor events and gatherings. Made from fiberglass-reinforced plastic, it provides a durable and spacious environment, catering to traditional Indian needs",
            img: "/image/img/FRP Portable Toilet Cabin ( Indian Style).png",
            features1: "Portable and Lightweight: Easy to transport and set up at various locations.",
            features2: "Easy Maintenance: Smooth surfaces facilitate quick and efficient cleaning.",
            feature3: "Hygienic Design: Equipped with modern toilet fixtures to ensure cleanliness.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 1",
             Tank:"  Tank Capacity- 100 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Toilet Cabin"
          },

         //  Double seated Toliet Cabins
          {
            id: 17,
            name: "Double Seated Toilet",
            Description:"The Double Seated Toilet offers a convenient and efficient solution for shared restroom facilities. Ideal for events, construction sites, and crowded venues, this portable toilet is designed for two users, promoting quicker access while maintaining comfort and privacy.",
            img: "/image/img/2 seater portable toilet cabin - Copy.png",
            features1: "Dual Seating: Accommodates two users simultaneously, ideal for high-traffic areas.",
            features2: "Hygienic Fixtures: Equipped with modern toilets for a clean and pleasant experience.",
            feature3: "Privacy Features: Secure locks and partitions for user privacy and comfort.",
            //  Wheel : "No of wheel- 2",
             Compartment:"No of Comapartment- 2",
             Tank:"  Tank Capacity- 200 ltr. Approx.",
             Brand:"Brand- HHES",
             Built:" Built Type-Modular",
             Wall:"Wall  Type-FRP",
             category:"Two Seater Toilet Cabin"
          },


          //Biogas Storage Tank

          {
            id: 18,
            name: "Bio Digester Tank",
            Description:"A bio digester tank, also known as a biodigester, is a sewage treatment system that uses anaerobic digestion to break down organic waste, including human waste, into methane gas and nutrient-rich effluent. This process occurs in an oxygen-free environment, making it an environmentally friendly and odorless method of waste treatment.",
            img: "/image/img/Bio Digester Tank.webp",
            features1: "Methane Production: Generates biogas, primarily methane, which can be captured and used as a renewable energy source.",
            features2: "Versatile Applications: Suitable for eco-friendly construction projects and off-grid locations.",
            feature3: "Space-Efficient Design: Ideal for areas with limited space or poor soil conditions, serving as an alternative to traditional septic tanks.",
            //  Wheel : "No of wheel- 2",
            //  Compartment:"No of Comapartment- 2",
             Tank:"Tank Capacity- 1500 ltr. Approx",
             Brand:"Brand- HHES",
             Built:" Built Type-FRP",
            //  Wall:"Wall  Type-FRP",
             category:"Biogas Storage Tank"
          },

          {
            id: 19,
            name: " Green FRP Bio Digester Tank",
            Description:"The FRP Bio Digester Tank is an advanced sewage treatment system designed to efficiently break down organic waste through anaerobic digestion. Made from fiberglass-reinforced plastic, it offers durability and resistance to corrosion, making it an ideal solution for eco-friendly waste management in various applications.",
            img: "/image/img/FRP Bio Digester Tank.png",
            features1: "Durable Construction: Made from fiberglass-reinforced plastic for longevity and corrosion resistance.",
            features2: "Biogas Production: Generates methane gas that can be harnessed for cooking, heating, or electricity.",
            feature3: "Nutrient-Rich Effluent: Produces partially treated effluent that can be safely reused for irrigation.",
            //  Wheel : "No of wheel- 2",
            //  Compartment:"No of Comapartment- 2",
             Tank:"Tank Capacity- 2000 ltr. Approx",
             Brand:"Brand- HHES",
             Built:" Built Type-FRP",
            //  Wall:"Wall  Type-FRP",
             category:"Biogas Storage Tank"
          },
          {
            id: 20,
            name: "  FRP Bio Digester Tank",
            Description:"The FRP Bio Digester Tank is an advanced sewage treatment system designed to efficiently break down organic waste through anaerobic digestion. Made from fiberglass-reinforced plastic, it offers durability and resistance to corrosion, making it an ideal solution for eco-friendly waste management in various applications.",
            img: "/image/img/Blue FRP Bio Digester Tank.webp",
            features1: "Durable Construction: Made from fiberglass-reinforced plastic for longevity and corrosion resistance.",
            features2: "Biogas Production: Generates methane gas that can be harnessed for cooking, heating, or electricity.",
            feature3: "Nutrient-Rich Effluent: Produces partially treated effluent that can be safely reused for irrigation.",
            //  Wheel : "No of wheel- 2",
            //  Compartment:"No of Comapartment- 2",
             Tank:"Tank Capacity- 2000 ltr. Approx",
             Brand:"Brand- HHES",
             Built:" Built Type-FRP",
            //  Wall:"Wall  Type-FRP",
             category:"Biogas Storage Tank"
          },

 ];
export default Data;
